### ISSUE TITLE
Client needs User Agent

### ISSUE THREAD

**Issue by NARKOZ** [bo-oz/vimeo_me2#15]
>Make sure to set a custom User Agent for your app. We will be much less likely to block access if we see a custom User Agent! We block certain generic User Agents now, and may block others in the future.

https://developer.vimeo.com/guidelines/best-practices#user-agents

**Comment by bo-oz** [comment]
Again, happy to accept a PR for this!

**Comment by bo-oz** [comment]
Added User Agent header in latest version. See following Commit: https://github.com/bo-oz/vimeo_me2/commit/c43a52b369a29c3b1c83ff579125a28ff5cfc206

Let me know if I can close this issue.

**Comment by NARKOZ** [comment]
Thank you.
