### ISSUE TITLE
Something strange occurred in PullUpload

### ISSUE THREAD

**Issue by mustafah** [bo-oz/vimeo_me2#19]
Hi everyone, 

I am getting VimeoMe2::RequestFailed, Something strange occurred. Please try again. Here is my story:
I was using the vimeo_client.pull_upload with no problem, I made an new vimeo app with API 3.4 and updated the vimeo_me2 to 1.2 . and it refuses to go through the upload process and in vimeo_me2/http/http_request.rb:24 the request returns the following :
{"error":"Something strange occurred. Please try again.","link":null,"developer_message":"To access upload features for API version 3.4 when your app defaults to a different API version, include the `Accept` header with your request, and set its value to `3.4`. For more details, see our versioning documentation at https://developer.vimeo.com/api/common-formats#versioning.","error_code":3116}
Everything seems ok, wonder what's causing this...

Thank you ...

**Comment by bo-oz** [comment]
Are you using a free account? Could it be that you are hitting the max of 10 daily uploads?

**Comment by mustafah** [comment]
No, I'm using Vimeo PLUS plan and my quota still 0 ... May be something related to my S3 bucket settings, the URL is publicly accessible though :)

**Comment by bo-oz** [comment]
To be completely honest, the pull method came in as a pull request. I didn't write the code myself. It looked pretty straightforward though. It seems that adding an Accept header would do the trick. Will you be able to adapt the pull method to incorporate this?

**Comment by bo-oz** [comment]
I see they changed the parameters that need to be set during a pull upload. I updated the method. Please update the code and see if it works.

**Comment by mustafah** [comment]
Thank you, but now in VimeoMe2::User.new it gives me:
```
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```
I'd be happy to incorporate any changes, but can you put me on the right direction ?

**Comment by mustafah** [comment]
I made a pull request about [this](https://github.com/bo-oz/vimeo_me2/issues/19#issuecomment-407055632) ...
It successfully pull upload the vide, but it fails for validating the response in vimeo_me2/http/http_request.rb:108 because the response changed and has no code ... Looking forward how to adapt that ...

**Comment by bo-oz** [comment]
I've changed the http status, so it should work now. Could you check again?

**Comment by bo-oz** [comment]
@mustafah were you able to test? I think the issue should no longer be occuring.

**Comment by mustafah** [comment]
I'm testing that tonight, I will tell the result of my trial ASAP, Thank you @bo-oz for your help

**Comment by mustafah** [comment]
for my initial test, it seems working now ... I will try it further again and report if there is any unexptected behaviour ...

**Comment by bo-oz** [comment]
Ok, I'll be closing this issue. Please raise a new one if the problem perists.
