### ISSUE TITLE
Rails Server not starting after Installing the gem

### ISSUE THREAD

**Issue by heitorado** [bo-oz/vimeo_me2#23]
Hello!

I'm using the gem with docker and docker compose. 
My rails version is 3.2.13.
My ruby version is 2.1.2.

After installing the gem as the README suggests, (which doesn't install at the first bundle install, I have to enter the container and do it again manually) I get the following error message after attempting to start the rails server:

```
rake aborted!
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/vimeo_me2-6d09c58acf06/lib/vimeo_me2/user/upload.rb:52: syntax error, unexpected ':', expecting =>
 ...     headers = {'Content-Type': 'application/offset+octet-st...
 ...                               ^
 /usr/local/lib/ruby/gems/2.1.0/bundler/gems/vimeo_me2-6d09c58acf06/lib/vimeo_me2/user/upload.rb:52: syntax error, unexpected '}', expecting keyword_end
 /rails_app/config/application.rb:9:in `<top (required)>'
 /rails_app/Rakefile:5:in `require'
 /rails_app/Rakefile:5:in `<top (required)>'
 (See full trace by running task with --trace)
```

Apparently this has been solved in this commit of one of the repo's forks:
https://github.com/BarefootCoders/vimeo_me2/commit/aa695e020df83d2a11291a7db835b33d5e1070f4

Any chance to integrate this to the master?

**Comment by bo-oz** [comment]
Hi,

Strange, because this seems like an error with a missing }. If it was there
already, it should have been found earlier. Are you sure it isn’t a local
problem? The latest build passed.

Thanks for checking.

Op ma 3 dec. 2018 om 18:18 schreef Heitor Carvalho <notifications@github.com

**Comment by heitorado** [comment]
Hey, thanks for the reply :)

Yeah, I found the second error pretty strange too. 
But forked it, modified he syntax and referenced my git fork to download the gem instead. Now it's working perfectly :)

**Comment by bo-oz** [comment]
Hmm strange. Could you do a pull request for the change? Happy to accept of
course.

Op di 4 dec. 2018 om 04:38 schreef Heitor Carvalho <notifications@github.com

**Comment by bo-oz** [comment]
Where you able to fix it? Could you let me know what the issue was?

**Comment by bo-oz** [comment]
I think this should fix: https://github.com/bo-oz/vimeo_me2/commit/e01880f0986194a6f696091757d22c809f203d30

**Comment by heitorado** [comment]
Yes, it was exaclty that!

Sorry for the _super late reply_... That was the change [I've made on my fork](https://github.com/Openredu/vimeo_me2/commit/92af3b6b8aae9115de5470bfb6d9e5cfebffdc34) and just today I realized I've completely forgot to send you the pull request

Glad you fixed it, thanks for the support!
:+1:
