### ISSUE TITLE
filesize too big? getting error: integer 2819140976 too big to convert to `int'

### ISSUE THREAD

**Issue by warnill** [bo-oz/vimeo_me2#24]

**Comment by warnill** [comment]
---BACKTRACE---- 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `syswrite' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `do_write' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:343:in `write' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:229:in `write0' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:203:in `block in write' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:220:in `writing' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:202:in `write' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/generic_request.rb:188:in `send_request_with_body' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `catch' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in `request' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1409:in `block in request' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start' 
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/gems/httparty-0.14.0/lib/httparty/request.rb:118:in `perform' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/gems/httparty-0.14.0/lib/httparty.rb:507:in `patch' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/gems/httparty-0.14.0/lib/httparty.rb:606:in `patch' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/bundler/gems/vimeo_me2-e01880f09861/lib/vimeo_me2/http/http_request.rb:24:in `public_send' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/bundler/gems/vimeo_me2-e01880f09861/lib/vimeo_me2/http/http_request.rb:24:in `make_http_request' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/bundler/gems/vimeo_me2-e01880f09861/lib/vimeo_me2/base.rb:38:in `request' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/bundler/gems/vimeo_me2-e01880f09861/lib/vimeo_me2/base.rb:18:in `block (2 levels) in ' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/bundler/gems/vimeo_me2-e01880f09861/lib/vimeo_me2/user/upload.rb:59:in `start_upload' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/bundler/gems/vimeo_me2-e01880f09861/lib/vimeo_me2/user/upload.rb:11:in `upload_video' 
/home/rails/backend/app/models/video.rb:69:in `upload_to_vimeo' 
/home/rails/backend/app/models/video.rb:107:in `transfer_vzaar_to_vimeo' 
/home/rails/backend/app/models/video.rb:100:in `block in vimeo_migration' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/gems/activerecord-5.2.1/lib/active_record/relation/delegation.rb:41:in `each' 
/home/rails/.rvm/gems/ruby-2.4.1@backend/gems/activerecord-5.2.1/lib/active_record/relation/delegation.rb:41:in `each' 
/home/rails/backend/app/models/video.rb:98:in `vimeo_migration'

**Comment by bo-oz** [comment]
Ruby should automatically switch to Bigint class. But I can't imagine that you are uploading a file that is bigger than 4611686018427387903 bytes, which is . 46k Gigabyte... Are you?

**Comment by bo-oz** [comment]
Hmm seems the error you have in the topic is talking about a different size... could be that some code in HTTParty is giving this error... You could test it by requiring a different version of HTTParty in the gem's gemspec. I see latest version is now 0.16.2

**Comment by warnill** [comment]
Thank you for your response, no the file is 2,7 gb. Yes i will try with the newer httparty version.

**Comment by warnill** [comment]
Tried httparty (~> 0.16.2), didnt help.

**Comment by bo-oz** [comment]
I'm struggling a bit with understanding how Vimeo_Me2 code is responsible for this error msg. Any ideas yourself?

**Comment by warnill** [comment]
hmm not sure, but i agree, the issue is probably something else. Thank you for your responses.
