### ISSUE TITLE
Change name of video at the time of upload

### ISSUE THREAD

**Issue by febincloudyuga** [bo-oz/vimeo_me2#25]
This line defaults the name of uploaded video to video.mp4
```
video = File.open('video.mp4')
vimeo_client.upload_video(video)
```
One way to change it now is by updating after upload using
`vimeo_video.name = "New name"`

Is it possible to give a name to it at the time of upload? Something like
`vimeo_client.upload_video(video, "New name")`

**Comment by febincloudyuga** [comment]
Just had a look at your code. Maybe we could do something like this ?
```
      def upload_video video,name=nil
        .
        .
        video = change_name_and_get_video name
```

**Comment by bo-oz** [comment]
I'd consider accepting a PR for such a change, as it sounds like a valuable addition. Would you consider writing the code? I'd go for a keyword paramater though:

```
      def upload_video video, name: nil
        .
        .
        video = change_name_and_get_video name
```

**Comment by bo-oz** [comment]
It seems I already prepared for such a use case, but forgot to include it in the public method. This should do it: https://github.com/bo-oz/vimeo_me2/commit/ad5801d7bcf5fd2e73f57315548a11e7b38a1d2f

**Comment by febincloudyuga** [comment]
Thank you!

**Comment by febincloudyuga** [comment]
I've updated and installed this gem and I still seem to be getting the same error
`vimeo_client.upload_video(video, "New name")`
> wrong number of arguments (given 2, expected 1)

Am I missing something?

**Comment by bo-oz** [comment]
Probably your version of the gem has not yet got the updated  code. I think
I need to bump the version number of that... let me try to do that later
today.

Op vr 15 mrt. 2019 om 05:25 schreef febincloudyuga <notifications@github.com

**Comment by febincloudyuga** [comment]
Great. Thanks!
