### ISSUE TITLE
Replace a video

### ISSUE THREAD

**Issue by febincloudyuga** [bo-oz/vimeo_me2#26]
Is it possible to have a functionality that would replace the source file of given video?

Please find the picture of documentation attached.

![Screen Shot 2019-03-15 at 10 00 26 AM](https://user-images.githubusercontent.com/29917673/54408831-84373880-4709-11e9-9409-ffddbab78d29.png)

**Comment by bo-oz** [comment]
I’d just upload a new video and delete the old one. Update your own record
after that to point to the new location. Again, happy to review and accept
a PR if you would be able to write this code.

Op vr 15 mrt. 2019 om 05:33 schreef febincloudyuga <notifications@github.com

**Comment by febincloudyuga** [comment]
I had done the same, but the problem lies when the video has embedded links. Since a new video generates a new `video_id`, the existing links become non-functional.

I'll check if I can send in a PR. Thanks.

**Comment by bo-oz** [comment]
Shouldn’t be too difficult to make! I’d have a look if I could find some
time, but unfortunately that’s not the case at the moment. Let me know if
you need any help!

Op vr 15 mrt. 2019 om 07:23 schreef febincloudyuga <notifications@github.com
