### ISSUE TITLE
Set domains

### ISSUE THREAD

**Issue by adominguez83** [bo-oz/vimeo_me2#30]
Hi!
Thanks in advance for this gem, it is very helpful. But I have a question, I can't configure the whitelisted domains, it's the only parameter that I can't edit, or even consult. Is it possible to perform that operation with this gem?
Regards!
Álvaro

**Comment by bo-oz** [comment]
It’s probably not in yet, if you can link to the variable in the API documentation I could have a look. Also happy to accept a PR for this, if you could write the code.

**Comment by adominguez83** [comment]
Hi!
Finally I did not need it, but I contribute the code with HTTParty in case someone needs it, I have verified that it works. 

auth = "Bearer #{TOKEN}"
HTTParty.put "https://api.vimeo.com/videos/#{video_id}/privacy/domains/example.com", headers: { "Authorization" => auth}

and also delete domains:

HTTParty.delete "https://api.vimeo.com/videos/#{video_id}/privacy/domains/example.com", headers: { "Authorization" => auth}

Regards!
