### ISSUE TITLE
VimeoMe2::RequestFailed

### ISSUE THREAD

**Issue by dineshebangar** [bo-oz/vimeo_me2#4]
I am uploading video on vimeo . Video get uploaded on vimeo successfully but while return request 
I got error "VimeoMe2::RequestFailed (Something went wrong)"  . 

Script : 

   vimeo_client = VimeoMe2::User.new('1254fg7856')
   data_url = vimeo_client.upload_video(video_file)

More_detail_error : 
  
    PATCH https://api.vimeo.com/videos/223757270455   
   204 No Content
   Completed 500 Internal Server Error in 352036ms
   VimeoMe2::RequestFailed (Something went wrong)

Thanks In Advance .

**Comment by bo-oz** [comment]
I'm going to have a look. Thanks for reporting this.

**Comment by bo-oz** [comment]
I pushed an update which I think will solve the issue. Could you let me know if it worked for you?

**Comment by bo-oz** [comment]
Please let me know if it solved your issue, otherwise I will close this issue. Thanks.

**Comment by dineshebangar** [comment]
Now its work for me .  Thank you so much .
